// Generated by CoffeeScript 1.3.1
(function() {

  window.throw_bowl = function(i) {
    window.pins.push(i);
  };
  window.getScore = function() {
     for (i=0; i < window.pins.length; i++) {
       window.score += window.pins[i];
     }
       
  }

}).call(this);
