// Generated by CoffeeScript 1.3.1
(function() {

  window.throw_bowl = function(i) {
    return window.pins.push(i);
  };

  window.getScore = function() {
    var i, _i, _len, _ref, _results;
    _ref = window.pins;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      i = _ref[_i];
      _results.push(window.score += i);
    }
    return _results;
  };

}).call(this);
